Fixed get_by_item_id query with ql parameter
Budabot/Tyrbot pull request #99
Opened 2020-12-15 22:29 UTC by deathlef

2020-12-16 06:40 UTC, Minidodo1 requested changes

2020-12-16 06:40 UTC, Minidodo1 commented on modules/standard/items/items_controller.py
> +            return self.db.query_single("SELECT * FROM aodb WHERE highid = ? OR lowid = ? ORDER BY highid = ? LIMIT 1", [item_id, item_id])
you forgot the third "item_id" param, i.e. "[item_id, item_id, item_id]"
For my Tests i added the third one as item_id.

2020-12-16 06:40 UTC, Minidodo1 commented on modules/standard/items/items_controller.py
> +            return self.db.query_single("SELECT * FROM aodb WHERE name = ? AND lowql <= ? AND highql >= ? ORDER BY highid DESC LIMIT 1", [name, ql, ql, item_id])
Here you added the 4th param, but didnt change the order by to "ORDER BY highid = ?"
in my tests, i removed the 4th param.

2020-12-16 17:05 UTC, bigwheels16 commented
I think this looks pretty good to me now

2020-12-21 11:01 UTC, Minidodo1 approved these changes
Yup, should work now - tested the same changes in my 3 bots so far, no issues till now 👍

2020-12-21 11:07 UTC, merged